version: "3.9"

# Services
services:

  # PHP Service
  php:
    build:
      context: ./php
      dockerfile: php-dockerfile

    extra_hosts:
        - host.docker.internal:host-gateway

    environment:
      TZ: "Europe/Amsterdam"
      DB_HOST: mariadb
      DB_NAME: laravel
      DB_USER: laraveluser
      DB_PASSWORD: laravel1234
    volumes:
      - '..:/var/www/html'
      - './php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'

    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    environment:
      TZ: "Europe/Amsterdam"
    links:
      - 'php'
    volumes:
      - '../public:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:10.9
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: laraveluser
        MYSQL_PASSWORD: laravel1234
        MYSQL_ROOT_PASSWORD: 1234db
        MYSQL_ROOT_HOST: "%" # Allow root login from anywhere
        TZ: "Europe/Amsterdam"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Copy the init.sql file to the container
    command: --init-file /docker-entrypoint-initdb.d/init.sql  # Run the SQL commands from the init.sql file

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      TZ: "Europe/Amsterdam"
    depends_on:
      - mariadb

# Volumes
volumes:
  mysqldata:
